### ISSUE TITLE
Volunteer Page - Design

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#101]
*******PLEASE SEE COMMENTS BELOW.*********
Utilize the master style guide in the Website style guide, design the volunteer page. Note that social media icons will match color, design, and scheme on Landing Page. Follow design in image below with the exception of the following:
[]Remove drop down arrow from Volunteer Navigation Bar.
[]Replace the text "Volunteer" in the navigation bar to "Register"
[]Replace "Dear Volunteers" located in the second column with "Dear Volunteers and Sponsors"
[]Make the Volunteer message in the second column where it reads "Thank you for considering getting involved...to life changing experiences." a modifiable label for the user. Circled yellow.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/9c76fbb3-1120-4be0-9581-ed0467dee559)

**Comment by chitownhope** [comment]
@dkaplan88 the volunteer page as presented in the staging site does not meet the design requirements.

**Comment by dkaplan88** [comment]
@chitownhope it appears the link is the issue the actual design and correct page lives here 

https://ymim-frontend-staging.herokuapp.com/volunteer

**Comment by hmichele** [comment]
Replace "Dear Volunteers" with "Dear Volunteers and Sponsors" as shown below:

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/2e153ae0-c321-49c0-b6e4-9f0274b85afe)
