### ISSUE TITLE
Fix:  Landing page/alignment of nav bar

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#126]
![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/8ccf7c55-0661-4040-962c-62e124332835)

**Comment by chitownhope** [comment]
Currently, the nav bar "About, Contact and Events" is not aligned to the left as by the design in the mockup (please, see screenshot).

**Comment by AdamRichey** [comment]
Finished, update is pushed to branch feature/96/header

**Comment by AdamRichey** [comment]
Re-opening issue, alignment not seen on last merge.

**Comment by chitownhope** [comment]
@dkaplan88 The alignment is still centered.  mockup has it left aligned.
