### ISSUE TITLE
FIX:  Home Page/alignment 

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#150]
Text should be aligned across the placeholdered pics.  Currently they are centered over the images.  See below:

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/9f8356e7-97e2-44ce-bda3-fc02d66cd2c8)

**Comment by Aleksandandar-Nedelkovski** [comment]
Resolved #160
