### ISSUE TITLE
Events Page - Change default image

### ISSUE THREAD

**Issue by JavaOfDoom** [the-difference-engine/ymim#177]
Change the default image for Event Card that will load if there is not an image already associated with the event on EventBrite. EventBrite images are formatted to be rectangular and the default image should also match that to make styling consistent. The current logo is square and changes the shape and size of the event card. Image ymim1.png in the assets folder matches images the client used in previous EventBrite posts./home/joe/Documents/the-difference-engine/ymim/frontend/src/assets/ymim1.png

**Comment by chitownhope** [comment]
@dkaplan88 a bit confused here...why was this ticket moved to backlog?  Is there something more that is needed in this ticket?
