### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#185]
As a user, I would like to view a page with information about supporting YMIMB so I can read more details and donate via PayPal.

Acceptance Criteria:
[]The text should meet the design requirements (see screenshot).
[]Donate Button (which is viewable on all pages, including Donate page) should direct to Paypal site.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/d3373bdc-dc30-4589-a1cc-b23629aa7e22)

**Comment by chitownhope** [comment]
@AimeeCasden Hi, Aimee.  Please, update the header, "Donate Now!" to be on one line.

**Comment by AimeeCasden** [comment]
i did ! Committed a pull request
