### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#186]
As an Admin User, I would like to login so that I can have access to backend features.

Acceptance Criteria:
[]Login access should be present in footer
[]Login screen should display per screenshot below.
[]Username should be 8 characters, comprised of alphas and numerals
[]When incorrect user name entered, an error message should be displayed.
[]Password should be 10 characters and be comprised of alphas, numerals and ONE special character
[]When incorrect password entered, an error message should be displayed.
[]If one or both fields are entered incorrectly, user should not be granted access.
[]User should have a link to recover password that says, "Forgot password" under button.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/c3512b9a-a75d-4d5e-bf22-996792051d4e)

**Comment by dkaplan88** [comment]
Just a heads up -> we removed the Forgot Password link, since that is going to be its own separate story 

also we will add the validations when we do the backend work!
