### ISSUE TITLE
Eventbright API architecture

### ISSUE THREAD

**Issue by ktburns214** [the-difference-engine/ymim#190]
determine how React frontend will interact with Django backend and Eventbright API

OAuth token to be stored in backend

contract for Eventbright API data:
FETCH request to Eventbright API ==> https://www.eventbriteapi.com/v3/users/me/events/ {
props {
key: id;
name, url, start, end, logo (if no image, use YMIM logo as default)
              }
}

**Comment by aliceluo2048** [comment]
See https://github.com/the-difference-engine/ymim/pull/182/commits/43c0df10ebae7306fd71761896583442035011c4
