### ISSUE TITLE
Landing Page: Upcoming Event in Mid-Section Dynamically Updates

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#192]
As a user, I want to see the next, upcoming event with respective details under "What's New" (mid section), so that I can learn what is new at YMIM and attend/participate in the event.

Acceptance Criteria:
[]When the an event has expired, the mid section should be updated with the next event and its details based on the Eventbrite feed.
[]if there is nothing upcoming in Eventbrite, content should read:
"Check back again soon for what's is coming up next for YMIM.  If you have an event that you think YMIM should be a part of please please email: Founder@theymim.org or call: 773.941.1200.."
[]Content should follow design requirements as implemented throughout the rest of the site.

**Comment by hmichele** [comment]
The following text needs to be changed from "If you have an event that you think YMIM should be a part of please please email: Founder@theymim.org or call: 773.941.1200" to "If you have an event that you think YMIM should be a part of, please email: Founder@theymim.org or call: 773.941.1200

**Comment by hmichele** [comment]
@diautzi Please add a comma before "please email..."

**Comment by diautzi** [comment]
It's done @hmichele
