### ISSUE TITLE
Landing Page Call to Actions in Header 

### ISSUE THREAD

**Issue by mpeoples81** [the-difference-engine/ymim#2]
As a user I want to be able to select  ABOUT, CONTACT US, ENROLL NOW, and GET INVOLVED within the header on the landing page so that I can chose which page I want to be navigated to.

Acceptance Criteria:
1) The landing page displays links to pages: ABOUT, CONTACT US, ENROLL NOW, GET INVOLVED
2) Users are able to click on each link and successfully navigate to the selected page

**Comment by scottgall** [comment]
created basic header component

waiting for wireframes to start styling
