### ISSUE TITLE
Landing Page: Dynamically update with most current event info.

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#206]
As a user, I would like to see a newly featured event being held by YMIM so that I can know what event is up and coming next.

Acceptance Criteria
[]The above information pertaining to the event should dynamically update with info of the next, upcoming event  (as events expire). ex.  the event that should be present would be for the current week vs. an event coming up in two weeks. 
[]The information should also update with the corresponding event date, title and description.
[]if there is nothing upcoming in Eventbrite, content should read:
"Check back again soon for what's is coming up next for YMIM. If you have an event that you think YMIM should be a part of please email: Founder@theymim.org or call:  773.941.1200."
[]Design of page should adhere to screenshot (with focus on padding; proper spacing around buttons; space above and bolding "RSVP and Find out More:"; and, removing underline of "Eventbrite" and "Facebook" upon hover.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/ef640b89-e88d-4cad-bbb8-cd866f9f9110)

**Comment by sunshyneDaCoder** [comment]
Removed the underline for the links...
