### ISSUE TITLE
FIX/DESIGN:  Formatting

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#211]
Formatting around text is still needed along with some padding around buttons.  
Please, remove underline that appears when links are hovered upon.

Please, see screenshot below:

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/7c78a8db-22ee-4e33-807c-eb73099f1cc6)

**Comment by ktburns214** [comment]
spacing between buttons completed, but link underlines still need to be removed
