### ISSUE TITLE
Events Page/Upcoming Event in Mid-Section: Mouse Over Functionality

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#216]
As a user, I want to be able to mouse over an event and see the event details such as event name, date, description. so that I can learn about an event without clicking on it.

Acceptance Criteria:
[]When the user mouses over an event, it should show event details such as event name, event date and description.
[]Content should follow design requirements as implemented throughout the rest of the site.
[]mouse over functionality would only be available on desktop.

**Comment by dkaplan88** [comment]
Going to move this to UAT -> just pushed the fix for the change I broke during the merging of the PRs -> will be live on staging shortly
