### ISSUE TITLE
SUB-NAV BAR: Volunteer

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#218]
As a user, I would like to click on the "Volunteer" in the sub-nav bar so I can be directed to the Volunteer form and information page.

Acceptance Criteria:
[] When user clicks on link, page will be redirected to volunteer form page (https://ymim-frontend-staging.herokuapp.com/volunteer).  
[] The 'Volunteer' link also needs to be highlighted in yellow when user is on the volunteer page.
[] Remove dropdown button.
[]Use the design mockup to ensure work aligns.

![Screen Shot 2019-08-26 at 8.02.13 PM.png]
(https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/c7f8a035-42f7-48e3-9871-0c6b0fc357f4)

**Comment by chitownhope** [comment]
@noemig57 this ticket has been updated.  Please, review acceptance criteria.

**Comment by chitownhope** [comment]
@dkaplan88 I am returning this to current sprint because while the acceptance criteria for this ticket has been fulfilled-- a different issue has emerged.  Also, this was Noemi's.  I am un-assigning her for someone else to pick this ticket up.  see screenshot.

**Comment by chitownhope** [comment]
@dkaplan88 my understanding is that @khanh-do is working on #247 (volunteer form) where her work might correct this when it is approved and merged.

**Comment by dkaplan88** [comment]
@chitownhope good catch, this was actually a bug introduced in the donate page. I just updated staging so should be good to go now https://ymim-frontend-staging.herokuapp.com/volunteer
