### ISSUE TITLE
FIX: Sub Nav Bar/Enroll

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#219]
As a user, I would like to click on the "Enroll" in the sub-nav bar so I can be directed to the Enroll form and information page.

Acceptance Criteria:
[] When user clicks on link, page will be redirected to volunteer form page (http://ymim-frontend-staging.herokuapp.com/enrollment).
[] The 'Enroll' link also needs to be highlighted in yellow when user is on the enroll page.
[] Remove dropdown button.

**Comment by hmichele** [comment]
The 'Enroll' link also needs to be highlighted in yellow when user is on the volunteer page.  Currently, it does not do that.
