### ISSUE TITLE
FIX:  Splash Page Design Formatting

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#231]
Acceptance Criteria:

[] Remove YMB logo located on the left side of the splash page below the navigation bar.
[] Change the spelling of "Masterbuilder" to "Masterbuilders"

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/5b76c7ab-70c2-42cc-ae8c-657522914948)

**Comment by chitownhope** [comment]
Hi, @khanh-do. Thanks for removing the logo per the client's request; however, it seems that more was taken away from the splash section than intended.  See below for what has been taken away.  Please, note that this unintentional change is affecting all of the pages where a splash is present.  Looping in @dkaplan88 for his awareness.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/13425d84-962e-4413-b119-877d159781f1)

**Comment by dkaplan88** [comment]
moving this back to UAT as discussed via Slack
