### ISSUE TITLE
FIX/DESIGN:  Refine Footer

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#232]
additional padding and a white line dividing the spaces between the bottom nav bar and copyright, etc section is needed.  Please, follow the screenshot below:

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/d0e301a6-582a-469c-89c8-80e3ee1a6f1a)

**Comment by chitownhope** [comment]
@dkaplan88 after speaking with Michele, it has been decided that the white line in the footer should be stretched across the entire footer.  We have shared this with @courtnaymcewen and she is aware.

**Comment by hmichele** [comment]
@courtnaymcewen This looks different from what you showed me yesterday.  Can you adjust the length of the footer so it leaves a bit of space between the left and right margins?
