### ISSUE TITLE
FIX:  EVENTS PAGE--GALLERY STYLIZATION

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#234]
[X]Increase font-size of "Past Events" header to:  36pt.
[X]Change background-color of events section to: #eeeaea
[]Change background-color of each events card to white with padding as estimated based on screenshot below.
[X]Increase margin between gallery rows estimated based on screenshot below.
[]Leverage the screenshot to closest approximation around padding or margin.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/a7fadd2a-ae4e-4e90-a95d-bf7ae66deff8)

**Comment by aliceluo2048** [comment]
@chitownhope The attached image has an "Invalid upstream response (403)"

**Comment by chitownhope** [comment]
@realwade1 I have re-uploaded the screenshot.  Let me know if you have any further questions.
