### ISSUE TITLE
FIX:  Contact Page/Splash Section

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#235]
Contact page should follow the design pattern as landing page, about page, enroll page.  It should have the splash section above the content as pictured in the screenshot below:

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/9518e537-3ec6-4abb-af39-e34cd611a389)

**Comment by hmichele** [comment]
@khanh-do Kim would like the splash section to be consistent with the home page.  Please change it to reflect the below:
![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/1d64a638-e9b3-44a5-bce1-2790b3465f75)

**Comment by khanh-do** [comment]
@hmichele @dkaplan88 @mkarazin 
I changed the heading of the splash section to "Young Masterbuilders in Motion" as requested.
