### ISSUE TITLE
EVENTS PAGE: Sponsors

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#236]
As a user I would like to visit the events page and learn about all of the sponsors that help support YMIM, so that I can learn how YMIM is able to support its initiative.

Acceptance Criteria:
[] section for sponsors should be created with white background in between the events section and the footer.
[]title:  "Our Sponsors"
[]Header should have same specs as in other pages
[]logos should be placed in an uniform, grid formatting
[]Image sizes should be as relative to one another as possible, i.e. none too small, none too large compared to the others.
[]12 sponsors should be included in the "Our Sponsors" section.  These images can be found in the assets folder.
[]Screenshot should be leveraged to determine general design specs.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/5b09efab-aeeb-4152-aafe-436e3d648ffc)

**Comment by chitownhope** [comment]
@JavaOfDoom Hi, Joe--there is a new sponsor added for this ticket==> children's dentistry of park ridge.  I have uploaded this into the frontend/assets folder via github

**Comment by hmichele** [comment]
@donhuey  Kim provided me with her sponsor logos and I have replaced them in github.  Please use the screenshot below as a reference. 

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/eced0175-fb2e-40ee-9c1d-2ed2c8149ffe)

**Comment by hmichele** [comment]
@khanh-do Please space the logos out a little bit.  You can modify the left and right margins to get extra space for the logos.
