### ISSUE TITLE
FIX:  Volunteer Page/Spash Section

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#239]
Volunteer page should follow the design pattern as landing page, about page, enroll page. It should have the splash section above the content as pictured in the screenshot below:

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/f7c243d0-b041-4447-8572-7fb1190307df)

**Comment by khanh-do** [comment]
As per discussion with @chitownhope and @hmichele, this ticket can be closed without further work done. At the time this ticket was created, there was no splash section. Since then, a splash section was added. For now, the splash image will be kept as-is.
