### ISSUE TITLE
Contact Page - Google Form

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#244]
As a potential ambassador or individual, I would like to input my information into the form so that I can learn more about YMIM.

Google forms will be used as a solution to capturing form data. It will be easy to create and update the form, see those changes immediately on the webpage and be easily transformed into a Google spreadsheet. Use the same fields as on the Contact Page in addition to the below.

Acceptance criteria:
[]Create Google docs form for contact form data.
[] Add a 'Interested in learning more' checkbox as the first item in the form.
[]All required fields must be completed in order to successfully submit form.
[]The Google spreadsheet will capture all data.

**Comment by hmichele** [comment]
@courtnaymcewen Please modify the google form and remove the address fields. The form should only have the following fields:

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/c0d9dd36-8b11-4644-b7cc-4948629743b4)

**Comment by courtnaymcewen** [comment]
@hmichele, I have updated the form.
