### ISSUE TITLE
Super Admin - Admin Users

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#25]
As a super admin, I would like to be able to view a list of all users, so that I can choose to make one or more users an admin user.

Acceptance criteria:

1. Viewable list of all users with user role
2. Option to make user or users an admin.

**Comment by mkirlin** [comment]
The work for this ended up getting split between two tickets; @dboston528 completed AC 1, and @scottgall & @dacogemini are working on AC 2 in the form of #64 (week of 3/18).
