### ISSUE TITLE
Volunteer Page: Upload video

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#254]
As a user, Kim would like to be able to upload videos and play them, so they can be visible and available on her site.  

Acceptance criteria:
[] Upload and embed videos.
[] Play videos.
[] Link 3 videos to the Volunteer Page on the right hand side.
[] There should be 3 header titles (Inspiring, Connecting, Empowering) displayed above each video and in that order.
[] Video size should be about 25% of the total width of the page. 
[] Follow the screenshot design below.

![image.png](https://images.zenhubusercontent.com/5cc7a2f3cb5df652d746324e/15ef82dd-c710-44f2-a468-31be3e71a2af)

**Comment by rbrodefrank** [comment]
The last video "Empowering" is no longer available, it is not playable on Youtube or on the current website https://www.theymim.org/enrollment/ Should I include it for now or just leave it out?

**Comment by hmichele** [comment]
@rbrodefrank You can include it for now and we'll replace it later.
