### ISSUE TITLE
FIX: CONTACT PAGE/TABLET VIEW and MOBILE VIEW

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#263]
[]Decrease line height of content next to form to:  30px
[]Decrease dimensions of button to:  width:  125px; height:  65px; font-size:  20px

**Comment by hmichele** [comment]
@khanh-do Per our conversation, please adjust the line spacing to be closer, modify the text to 'accompanying form'  instead of 'form below' and move the phone information to the next line.
