### ISSUE TITLE
FIX/DONATE PAGE: Donate Button

### ISSUE THREAD

**Issue by chitownhope** [the-difference-engine/ymim#282]
Kim would like the donate button enlarged.

Acceptance Criteria
[] Resize the donate button to 100 px.

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/59271ec9-7ee8-4be4-95e7-e74d989a1fa8)

**Comment by chitownhope** [comment]
@dkaplan88 Hey, Dan--was looking into revising the donate but as you and I discussed a couple of weeks ago.  I found some info online. @hmichele is uncertain that this will be possible due to some underlying code.

**Comment by hmichele** [comment]
Please follow the new criteria above.
