### ISSUE TITLE
About Page - Design

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#299]
Kim would like the background photo on the About page to be unique. Use the screenshot below as a guide on how to model the new photo.

Acceptance Criteria:
[] Replace the existing photo on the page with the following photo: 
![groupofwomen.jpg](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/73519485-3e17-4955-a34c-ab1d4dc89e9e)

[] Make sure the photo size is the same as the original photo on the About page.
[] Modify the photo so it has a hazy look as the original photo on the About page.

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/44d90167-0265-43ca-a3e3-f7377bcc88b3)

**Comment by hmichele** [comment]
@diautzi Please also capitalize the I in the subheader and bold the following text: "inspires, connects, and empowers young women orphans, adoptees, and foster youth alumnae to thrive."

**Comment by diautzi** [comment]
Ok, I’ll do that

**Comment by hmichele** [comment]
@diautzi The photo in the splash section was not replaced.
