### ISSUE TITLE
FIX: Volunteer Page - Mobile View

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#308]
The text on the mobile view version of the Volunteer page needs to be consistent with the About Page, which is left justified.

Acceptance Criteria:
[]Make the text indicated in the screenshot left justified.

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/83f26a30-1d05-49e8-b6af-43b24d4b42bf)

**Comment by hmichele** [comment]
Please increase the spacing.  Currently, it is too close to the first paragraph as shown in the screenshot.

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/3724cbe8-0e02-45f8-987b-66f767e3f9aa)

**Comment by diautzi** [comment]
@hmichele: I increased the spacing between the title and the paragraph. please let me know if you like it: 
![Screen Shot 2019-11-13 at 7.17.26 PM.png](https://images.zenhubusercontent.com/5db788421484010001787fbf/28445450-a73c-44c5-a636-e691424def23)

**Comment by hmichele** [comment]
@diautzi @dkaplan88  I'm not sure what happened, but the text is still centered in mobile view.
