### ISSUE TITLE
FIX: Enroll Page Google Form - Limit Text Field Characters 

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#322]
It is important to limit the number of characters in fields on the form, so there isn't an unlimited amount of data captured.

Acceptance Criteria:
[] Name field should be limited to 50 characters
[] Email field should be limited to 30 characters
[] Message field should be limited to 200 characters.

**Comment by hmichele** [comment]
@SoniaDumitru The name field does not meet the acceptance criteria above.  Please check.

**Comment by hmichele** [comment]
@SoniaDumitru Please include the 50 characters limit in the Name error message.

**Comment by SoniaDumitru** [comment]
Done, code is ready for review.

![Screen Shot 2019-12-16 at 10.24.45 PM.png](https://images.zenhubusercontent.com/5db7880cb233b50001b2c94c/1a4ed3fd-cf55-4588-a13e-522070332ad8)![Screen Shot 2019-12-16 at 10.24.34 PM.png](https://images.zenhubusercontent.com/5db7880cb233b50001b2c94c/ec8544d1-9ece-4244-a248-78c14771b256)
