### ISSUE TITLE
FIX: Contact Page Google Form - Limit Text Field Characters

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#324]
It is important to limit the number of characters in fields on the form, so there isn't an unlimited amount of data captured.

Acceptance Criteria:
[] Name field should be limited to 50 characters
[] Email field should be limited to 50 characters
[] Message field should be limited to 200 characters.

**Comment by diautzi** [comment]
![Screen Shot 2019-11-19 at 12.09.32 PM.png](https://images.zenhubusercontent.com/5db788421484010001787fbf/f9ddf405-c5b7-4239-8fc5-49fef4e53fcf)
![Screen Shot 2019-11-19 at 12.09.19 PM.png](https://images.zenhubusercontent.com/5db788421484010001787fbf/74d62d6f-7b82-450a-a7cd-93e7303a7cef)
![Screen Shot 2019-11-19 at 12.08.56 PM.png](https://images.zenhubusercontent.com/5db788421484010001787fbf/30374cf9-f3a7-4b6d-a1bf-2124dab46247)!
![Screen Shot 2019-11-19 at 12.07.48 PM.png](https://images.zenhubusercontent.com/5db788421484010001787fbf/e918fe30-5b94-4a2f-aa91-36c6a00247e5)

**Comment by hmichele** [comment]
@diautzi Please check the name field.  It still shows the error message when there are 50 or less characters.

**Comment by diautzi** [comment]
Ok
