### ISSUE TITLE
Documentation: Volunteer - Google Forms

### ISSUE THREAD

**Issue by JigSays** [the-difference-engine/ymim#425]
As an Admin, I would like to be able to know how to access and update the Google Form on the 'Volunteer' page of the site, how to access the information once a visitor submits the form, and how to change the notification settings where the form submissions are received. 

![Screenshot 2020-02-20 20.11.09.png](https://images.zenhubusercontent.com/5a7202374b5806bc2bc51343/4d1c44d3-2b66-4aa9-8dd9-f4fc85293d94)

Acceptance Criteria:

- [ ] Admin needs to know how to access the hosted area of the Google Form

- [ ] Admin needs to know how to make changes to the Google Form

- [ ] Admin needs to know how to access the data once the Google Form is submitted

- [ ] Admin needs to know how to change the notification settings for the Google Form

- [ ] Admin needs to know for to change the delivery method of the notifications for the Google Form

- [ ] Admin needs to know the credentials for accessing the Google Forms account. 
[] Screenshots and step by step instructions need to be included.

**Comment by hmichele** [comment]
@iquinterom 

Please see below:

- The documentation should only be for the Volunteer Google form.  Please remove "Sponsors".
- Make the instructions pertain to the Volunteer Google form only.  Remove anything that references other forms.
-  Please include the password for the YMB email account.
- Number each step.

- Highlight/label each icon when referencing, so it's easier to spot.
![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/6deafe33-120a-49cd-8178-f15fceedbc68)

- Bold each section and add spacing to differentiate section.
![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/7c3c7b44-0918-4eaf-8c9a-ac3a046482a8)


- Detail and explain every step.
- Add screenshots for every step.

**Comment by hmichele** [comment]
@iquinterom I have sent your pdf with Jordan's (10) comments.  The file was too large to attach here.

Please also see below:

- Please add a screenshot that shows where you enter the login and password information on the page.  
- Make sure numbering is correct.  Some were off.

**Comment by hmichele** [comment]
@iquinterom 

Please see below:

The documentation needs to pertain to the Volunteer form, but I'm seeing things on the screenshot that aren't for the form.

- In **Adding questions 6c. - f.** shows "agent" as an option instead of "organization". Why is that there?  Please correct the form and documentation.

- in **Downloading responses as a .csv file step 5** - Add the text: 'folder' after the "Downloads" text.

-  Please make sure only the ymim.forms@gmail.com account has access and is able to edit this form.
