### ISSUE TITLE
Events Calendar within the events page

### ISSUE THREAD

**Issue by mpeoples81** [the-difference-engine/ymim#71]
As a user I want to be able to view a 30 day events calendar, so that I can view upcoming and past YMIM events.

Acceptance Criteria:
1. There is a 30 day events calendar that starts from the day the user is viewing the calendar
2. Super Admin is able to add and delete events from the calendar
3. Will have a basic 30 day calendar design until we are able to get more details from the client on her preferred design.

*please reach out to the PM with any questions or suggestions you have about this feature. Suggestions welcomed!

**Comment by sudo-eddy** [comment]
Closing this issue, we are no longer using a calendar option.
