### ISSUE TITLE
Enroll Now- Student Application Form

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#76]
As a user, I want to be able to click on the "Enroll Now" menu button so that I can be taken to an enrollment page where I can submit an application and personal statement to become a program participant.

Acceptance Criteria:

1. A menu button that when clicked takes me to the enrollment page.
2. An application with data fields where I can enter my name, contact information, email, and a personal statement.
3. The application will contain the content in the attached images
4. The Enrollment page will contain the same copy as the attached images

**Comment by mpeoples81** [comment]
![Screen Shot 2019-03-28 at 6 40 40 PM](https://user-images.githubusercontent.com/46844453/55200162-f6d4f900-518a-11e9-912f-f4afc8949b85.png)
![Screen Shot 2019-03-28 at 6 40 16 PM](https://user-images.githubusercontent.com/46844453/55200166-fb011680-518a-11e9-9ee5-bbf074a94eb7.png)
