### ISSUE TITLE
Resources menu button on Landing Page

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#77]
As a user, I want to be able to click on a menu button called "Resources" so that I can be navigated to a page that contains resources.

Acceptance Criteria:
1. A menu button that navigates to an additional Resources page.

**Comment by sudo-eddy** [comment]
Unable to see Resources button when going to the frontend, confirmed by @dacogemini. I'm working on creating this button as a dropdown on #79, since we only completed the backend for that ticket.
