### ISSUE TITLE
Social Media Icons - Page Headers

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#93]
As a user, I'd like to be able to click on one of three social icons (Facebook, Instagram, Twitter) on the header of any page so that I can connect to YMIM's social media platform directly via a new window.

Acceptance Criteria:
1. A social icon for each platform (Facebook, Instagram, Twitter) that connects me directly to YMIM's platform.
2. Each social icon style and color should match the ![Home_wHeavierType-min.png](https://images.zenhubusercontent.com/5c5ce522ebd8ee7342dd6d78/cce2b99d-5638-4f05-b566-f950af6c9db1)social media icon public color scheme.
3. A working link that works on one click of the social icon.
4. A new window opens the YMIM social media platform.

**Comment by sudo-eddy** [comment]
Moving social media to footer on mobile view

**Comment by sudo-eddy** [comment]
This issue has been fixed by #117
