### ISSUE TITLE
Landing Page - Style (1 of 3) - Header Section

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#94]
Create a Landing Page according to the attached style in image. A style guide is available for additional reference for font, color, typography specifications.
Acceptance Criteria:
1. Working Donate Button and style.
2. Logo
3. Social Media icons
4. Drop down buttons for Navigation Bar
5. Working carousel

**Comment by Auprodmgrdf** [comment]
![Screenshot from 2019-05-02 19-28-28.png](https://images.zenhubusercontent.com/5c5ce522ebd8ee7342dd6d78/7f838d74-009c-4156-8d74-3fdd95565050)

**Comment by Auprodmgrdf** [comment]
![Screenshot from 2019-05-02 19-31-10.png](https://images.zenhubusercontent.com/5c5ce522ebd8ee7342dd6d78/690c6a53-2466-41df-9de8-5639ca7fcbf3)

**Comment by sudo-eddy** [comment]
This issue has been fixed by #117
