### ISSUE TITLE
Landing Page - Style (2 of 3) - Midsection

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#95]
Following attached mockup![Screenshot from 2019-05-02 19-31-38.png](https://images.zenhubusercontent.com/5c5ce522ebd8ee7342dd6d78/5a3d5661-f7ca-40ca-81c5-bb2816466462) image:

**Comment by chitownhope** [comment]
@dkaplan88 issue requires more alignment to the mockups included in this issue.  Some of the outstanding alignment issues are:

*Text is not in bold font according to mock up
*Spacing around each of the 3 buttons on the page
*Eventbrite and Facebook links are missing
*space above "Who Are We" is too narrow on staging site
*text under Enroll button should be Hex:  697689

**Comment by chitownhope** [comment]
content under Enroll button should be centered.
